# V3 syntax
version: '3.8'

services:
    db:
        image: postgres:alpine
        container_name: eduke-db
        restart: always
        environment:
            - POSTGRES_USER=eduke
            - POSTGRES_PASSWORD=eduke
        volumes:
            -  postgres:/var/lib/postgresql/data
        ports:
            -  '5432:5432'
    # Caching with Redis
    cache:
        image: redis:latest
        container_name: eduke-redis-cache
        command: --appendonly yes
        volumes:
            -  eduke-redis-data:/data
        ports:
            -  '6379:6379'
    api:
        image: caddy:alpine
        container_name: eduke-api
        volumes:
            -  .:/var/www/eduke
        restart: unless-stopped
        ports:
            -  '80:8082'
        depends_on:
            - db
        links:
            -   cache
# Volumes
volumes:
    postgres:
        driver: local
    eduke-redis-data:
        driver: local
